name = "Pure Mathematics with Lean"
version = "1.0.0"
extra_files = "extras"
intro = "src/game/intro.lean"

[[worlds]]
name = "Equations"
id = 1
levels = [
	"src/equations/refl/level.lean",
	"src/equations/commutativity_rw/level.lean",
	"src/equations/rw_with_local_hypotheses/level.lean",
	"src/equations/focussed_rewriting/level.lean",
	"src/equations/associativity/level.lean",
	"src/equations/structured_proofs/level.lean",
	"src/equations/multiple_rewrites/level.lean",
	"src/equations/backward_rewrite/level.lean",
]

[[worlds]]
name = "Functions"
id = 2
parents = [1]
levels = [
	"src/function/defining_functions/level.lean",

]


