name = "Pure Mathematics with Lean"
version = "1.1.1"
extra_files = "extras"
intro = "src/game/intro.lean"

[[worlds]]
name = "Equations"
id = 1
levels = [
	"src/equations/refl.lean",
	"src/equations/commutativity_rw.lean",
	"src/equations/rw_with_local_hypotheses.lean",
	"src/equations/focussed_rewriting.lean",
	"src/equations/associativity.lean",
	"src/equations/structured_proofs.lean",
	"src/equations/multiple_rewrites.lean",
	"src/equations/backward_rewrite.lean",
	"src/equations/additive_identity.lean",
	"src/equations/universal_statements.lean",
	"src/equations/unique_additive_identity.lean",
	"src/equations/additive_inverse.lean",
	"src/equations/cancellation_i.lean",
	"src/equations/unique_additive_inverse.lean",
	"src/equations/simplifier.lean",
	"src/equations/algebraic_structures.lean",
]

[[worlds]]
name = "Strong Induction"
id = 2
parents = [1]
levels = [
	"src/strong_induction/introduction.lean",
	"src/strong_induction/different_base_case.lean",
	"src/strong_induction/minimal_element.lean",
	"src/strong_induction/well_ordering_principle.lean",
]

[[worlds]]
name = "Divisibility"
id = 3
parents = [1]
levels = [
	"src/divisibility/dvd_definition.lean",
	"src/divisibility/dvd_refl.lean",
	"src/divisibility/dvd_mul_of_dvd_left.lean",
	"src/divisibility/mul_dvd_mul.lean",
	"src/divisibility/dvd_mul_add_mul.lean",
	"src/divisibility/dvd_trans.lean",
	"src/divisibility/dvd_antisymm.lean",
	"src/divisibility/common_divisors.lean",
	"src/divisibility/common_divisors2.lean",
	"src/divisibility/gcd_uniqueness.lean",
	"src/divisibility/gcd_zero.lean",
	"src/divisibility/gcd_comm.lean",
	"src/divisibility/division.lean",
	"src/divisibility/bezout.lean",
	"src/divisibility/gcd_neg.lean",
	"src/divisibility/bezout2.lean",
	"src/divisibility/euclid_basic.lean",
	"src/divisibility/euclidean_algorithm.lean",
]


