name = "Pure Mathematics with Lean"
version = "1.0.0"
extra_files = "extras"
intro = "src/game/intro.lean"

[[worlds]]
name = "Equations"
id = 1
levels = [
	"src/equations/refl.lean",
	"src/equations/commutativity_rw.lean",
	"src/equations/rw_with_local_hypotheses.lean",
	"src/equations/focussed_rewriting.lean",
	"src/equations/associativity.lean",
	"src/equations/structured_proofs.lean",
	"src/equations/multiple_rewrites.lean",
	"src/equations/backward_rewrite.lean",
	"src/equations/additive_identity.lean",
	"src/equations/additive_inverse.lean",
]

[[worlds]]
name = "Functions"
id = 2
parents = [1]
levels = [
	"src/function/defining_functions/level.lean",

]


