import  group.negative_powers -- hide

/-
# Groups

## Level XX: Dihedral groups
-/


namespace exlean -- hide

open group -- hide

namespace dihedral -- hide

variables {D12 : Type*} [group D12] -- hide

variables {r s : D12} -- hide

/-
Let $n \ge 2$ be an integer. The dihedral group $D_{2n}$ is a finite group generated by two
elements $r$ and $s$ satisfying the relations $r ^ n = 1$, $s ^ 2 = 1$, and
$s \ast r = r^{-1} \ast s$.

Geometrically, $D_{2n}$ is the group of symmetries of a regular $n$-gon. The element $r$ represents
a rotation of $2\pi/n$ about the centre of the $n$-gon while $s$ represents the reflection in the
line through a (fixed) vertex and the origin.

## Task

* By hand, write a proof by induction that if $k$ is a natural number, then
$s \ast r ^ k = r ^{-k} \ast s$. We call this result `dihedral_swap`. See below for the Lean proof.
-/


/- Axiom : dihedral_swap
{k : ℕ}  : s * r ^ k = r ^ (-(k : ℤ)) * s 
-/
lemma dihedral_swap (h : s * r = r⁻¹ * s) {k : ℕ} :
  s * r ^ k = r ^ (-(k : ℤ)) * s :=
begin
  induction k with k ih,
  { simp, },
  { simp only [pow_succ, ←pow_mul_comm', ←mul_assoc, ih, gpow_neg],
    norm_cast,
    simp only [pow_succ, mul_inv_rev],
    rw [mul_assoc, h, ←mul_assoc], },
end

/-
## Task
* We'll now work in the dihedral group $D_{12}$. Show that there exist natural numbers $i$ and $j$
such that $s ^ 3 \ast r ^ i = r ^ i \ast s ^ j$.
-/

variables (hr : r ^ 6 = 1) (hs : s ^ 2 = 1)

include hr hs -- hide

lemma mul_inv_revd (h : s * r = r⁻¹ * s) :
  ∃ (i j : ℕ), s ^ 3 * r ^ 8 = r ^ i * s ^ j  :=
begin
  use [4,1],
  calc s ^ 3 * r ^ 8 = s ^ (2 + 1) * r ^ 8 : by refl
  ... = (s ^ 2 * s ^ 1) * r ^ 8 : by rw pow_add
  ... = (1 * s ^ 1) * r ^ 8 : by rw hs
  ... = (1 * s) * r ^ 8 : by rw pow_one
  ... = s * r ^ 8     : by rw one_mul
  ... = r ^ (-((8 : ℕ) : ℤ)) * s : by rw dihedral_swap h
  ... = r ^ 4 * s ^ 1 : _,
  rw [pow_one, mul_right_cancel_iff, gpow_neg, gpow_coe_nat],
  apply inv_eq_of_mul_eq_one,
  rw [←pow_add],
  rw show 8 + 4 = 6 * 2, by refl,
  rw [pow_mul, hr, one_pow],







end 

end dihedral -- hide

end exlean -- hide